import uuid
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, Cookie
from sqlalchemy.orm import Session

from db.database import get_db
from models.job import StoryJob
from schemas.job import StoryJobResponse

router = APIRouter(
    prefix="/jobs",
    tags=["jobs"]
)

@router.get("/{job_id}", response_model=StoryJobResponse)
def get_job_status(job_id: str, db: Session = Depends(get_db)):
    job = db.query(StoryJob).filter(StoryJob.job_id == job_id).first() # return: SQLAlchemy StoryJob object

    
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    return job # FastAPI converts JSON-serializable format generated by the Pydantic model to JSON text for HTTP transmission. Pydantic does the heavy lifting (validation + serialization), FastAPI just takes the result and sends it as JSON.

"""
1. You return: job (SQLAlchemy object)
   ↓
2. FastAPI sees: response_model=StoryJobResponse
   ↓
3. FastAPI calls Pydantic: StoryJobResponse.model_validate(job)
   ↓
4. Pydantic (with from_attributes=True):
   └─ Reads: job.job_id, job.status, job.created_at, etc.
   └─ Validates: Types match? DateTime is valid?
   └─ Returns: Pydantic model instance (JSON-serializable format)
   ↓
5. FastAPI converts Pydantic model to JSON text
   └─ Calls: pydantic_model.model_dump_json()
   └─ Result: '{"job_id": "123", "status": "pending", ...}'
   ↓
6. FastAPI sends JSON text in HTTP response
   ↓
7. Browser receives JSON text

# Step 3-4: Pydantic does validation and conversion
class StoryJobResponse(BaseModel):
    job_id: str
    status: str
    
    class Config:
        from_attributes = True

# Pydantic essentially does this:
pydantic_instance = StoryJobResponse(
    job_id=job.job_id,           # Reads attribute
    status=job.status,           # Reads attribute
    created_at=job.created_at    # Converts datetime to string
)
# Result: A validated Pydantic model

# Step 5: FastAPI converts to JSON
json_text = pydantic_instance.model_dump_json()
# Result: '{"job_id": "123", "status": "pending", "created_at": "2026-02-23T10:00:00"}'

# Step 6: FastAPI sends in HTTP response
response = Response(content=json_text, media_type="application/json")
"""