# represent the intent to create the story

from sqlalchemy import Column, Integer, String, DateTime
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from db.database import Base
"""
Since a story takes time to be generated by a LLM, we need a workflow to manage the story generation process. Specifically, when someone submits a request to generate a story, it won't be created rightaway. Thus, we will keep checking the status of job until it is completed and once it is completed, the story will be finished and we can grab it.


The workflow is as follows:
The frontend submits a request for the job.
The backend receives the request and creates a new job.

The frontend asks if the job is done.
The backend checks the status of the job and returns the result to the frontend.

If job is done, backend can send story.
"""

class StoryJob(Base):
    __tablename__ = "story_jobs"

    id = Column(Integer, primary_key=True, index=True)
    job_id = Column(String, index=True, unique=True)
    session_id = Column(String, index=True)
    theme = Column(String)
    status = Column(String)
    story_id = Column(Integer, nullable=True) # can be null or empty
    error = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True) # can be null or empty since the job is never completed or failed